### ISSUE TITLE
new bracketing stuff

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#1]
@jhuggins how do the new bracketing commands around here:

https://github.com/trevorcampbell/shortex/blob/c5ec2d0142e0a586d5b7e778dd5122dcdb3df3da/shortex.sty#L117

https://github.com/trevorcampbell/shortex/blob/c5ec2d0142e0a586d5b7e778dd5122dcdb3df3da/shortex.sty#L142

compare to the `\pp` ones I added a while back:

https://github.com/trevorcampbell/shortex/blob/c5ec2d0142e0a586d5b7e778dd5122dcdb3df3da/shortex.sty#L134

? 

Can you pull the new README from `master` into this branch and add some examples too?

**Comment by jhuggins** [comment]
The more important one is what comes after it (`\lcrx`), which does auto-resizing or fixed resizing; and no resizing if inline. 

This is then used below to define more convenient commands for bracket(-like) pairs, starting here:

https://github.com/trevorcampbell/shortex/blob/a442d876781bd531ad1bf6871cfc9309071ae6fe/shortex.sty#L143

Check out the examples here: https://github.com/trevorcampbell/shortex/blob/a442d876781bd531ad1bf6871cfc9309071ae6fe/example.pdf

I think we should add to [example.tex](https://github.com/trevorcampbell/shortex/blob/a442d876781bd531ad1bf6871cfc9309071ae6fe/example.tex) rather than the readme (and maybe rename it to readme.tex). That way we can display the results of pieces of LaTeX code.

**Comment by trevorcampbell** [comment]
> I think we should add to example.tex rather than the readme (and maybe rename it to readme.tex). That way we can display the results of pieces of LaTeX code.

I agree. I think we should keep the readme.md with a smaller subset of examples, but have a demonstration of all features in example.tex. I'll open an issue about that (maybe a good first one for Jeff).

But I like your changes (although we may change syntax as part of #2) , so you should PR/merge this branch into master.

**Comment by jnegrea** [comment]
I think that the default behaviour for lcrx being different inline vs. math mode is a good idea (not something I originally had). I think that when given optional arguments it should still resize to the user specified value --- essentially having the default argument set to 0 instead of -1 inline, but still having optional arguments actually change the behaviour would be better. Thoughts?

**Comment by jhuggins** [comment]
@jnegrea so you propose to basically revert to your original version but change the default argument to `0`?

**Comment by jnegrea** [comment]
im not sure how you made the behaviour different inline, but if possible make the difference just what the default value is inline, instead of the entire behaviour

**Comment by jhuggins** [comment]
I see. I'm use `\mathchoice` as suggested here: https://tex.stackexchange.com/questions/389459/test-for-inline-math-mode/389461

Probably the best approach is to have an if else that converts some special default (e.g., -2) to either -1 or 0 using \mathchoice. I think the following version which makes use of your original `\lcrx` command would work:
```latex
\newcommand{\lcrxx}[4][{-2}]{
	\IfEq{#1}{-2}{\mathchoice{\lcrx[-1]{#2}{#3}{#4}}
				 {\lcrx[0]{#2}{#3}{#4}}
				 {\lcrx[0]{#2}{#3}{#4}}
				 {\lcrx[0]{#2}{#3}{#4}}}
		     {\lcrx[#1]{#2}{#3}{#4}}}
```
