### ISSUE TITLE
Some missing prefixed symbols

### ISSUE THREAD

**Issue by trevorcampbell** [trevorcampbell/shortex#4]
In the style file there are some commented out prefixed symbols (e.g. some of the `\b...` symbols). I imagine this is because of a clash with some base latex command. 

We should figure out what to do about these -- ideally keep the super short prefixes we have now and get rid of the preceding definition, if it doesn't muck anything basic up...

**Comment by jhuggins** [comment]
I'm also not super attached to the "bold or bar" functionality. I think having `\b...` will be a problem if we want consistency since, e.g., `\bf` is not something to overwrite (Right now the bold or bar f command is `\bbf`.) So, we could do `\bb...` for all the bolds, `\bar...` for bars, and `\b?...` for bolds combined with other things (e.g., `\bi...` for bold italics).

**Comment by jhuggins** [comment]
I believe this has been addressed by #7, so closing for now.
