### ISSUE TITLE
Automatic environment macro generation, star versions

### ISSUE THREAD

**Issue by jhuggins** [trevorcampbell/shortex#8]
As described here: https://tex.stackexchange.com/questions/376375/using-ifstar-to-define-a-star-variant/376380

**Comment by jhuggins** [comment]
@jnegrea I wonder if you could use your new knowledge of auto-command generation for this. For theorem, the commands you need are:
```latex
\newcommand{\bthm}{\@ifstar{\begin{theorem*}}{\begin{theorem}}}
\newcommand{\ethm}{\@ifstar{\end{theorem*}}{\end{theorem}}}
```
So, it would be nice to be able to auto-generate these with a command like
```latex
\maketheoremshortcuts{theorem}{thm}
```

**Comment by jnegrea** [comment]
what is the utility of these commands and what is the pattern to auto-generate?
Is the utility that "\begin{theorem}" is "too long" to type out? 
If so, I think I disagree with whether the character savings are worth using these macros.

Also, to auto-generate them we would need some kind of pattern matching between the environment name and the command we want to use, so we would either need to define the theorem environment as 
`\declaretheorem[name=Theorem,numberwithin=section]{thm}
`
or we would need the macro to look like `btheorem` instead of `bthm` (or have a common rule to go from the long name to the short name---like drop all vowels--- or essentially build a lookup table for the names). I don't really like any of these options too much.

There could be utility in having a command that defines all theorem like environments that are "numberlike=x" with one command, and all starred versions of those, but that maybe would be separate from the \bthm \ethm shorthands...

Thoguhts?

**Comment by jhuggins** [comment]
I wasn't thinking of something quite so automated. Just something like
```latex
\maketheoremshortcuts{theorem}{thm}
\maketheoremshortcuts{lemma}{lem}
\maketheoremshortcuts{proposition}{prop}
```
and so forth. 

Why don't you think it is worth the savings to have shortcuts?

I do like the idea of having a package option for how to number the theorem-like environments. 

Any thoughts @trevorcampbell?

**Comment by trevorcampbell** [comment]
> Is the utility that "\begin{theorem}" is "too long" to type out?
> If so, I think I disagree with whether the character savings are worth using these macros.

I'm with @jhuggins : `\begin{theorem}` is both super long and contains curly braces, which requires wrist gymnastics. `\bthm` is significantly faster and no special chars. I've been using `\bthm`-style shortcuts for ages now and it's a big improvement in readability and efficiency for theory-heavy papers.

I also like the idea of package option for numbering style.

I am also on board with "not so automated" -- the suggestion @jhuggins made looks exactly right to me.

**Comment by trevorcampbell** [comment]
as an addendum -- the reason why automated command generation is nice for the character modifiers (e.g. `\h...` and `\t...`) is because there are a huge number of characters to which they apply. More automation here is good for maintainability.

For shorthand theorem-like environments, there's really only about 10 or so of them, so not a big deal to handle them individually.

**Comment by jnegrea** [comment]
should other environments get similar treatment then, eg table, tabular, matrix, cases, etc? all of these require \begin{...}...\end{...}

**Comment by jhuggins** [comment]
Good question. Those are mostly used less but that could make sense. At some point I definitely had shortcuts for matrix environments. Perhaps we should make separate discussions for within-equation environments and figure-like environments.

**Comment by trevorcampbell** [comment]
> should other environments get similar treatment then, eg table, tabular, matrix, cases, etc? all of these require \begin{...}...\end{...}

yeah! that would actually be awesome. Currently we have the theorem-like environments and lists (`\bitems ... \eitems` and `\benum... \eenum`). I think we can limit it to the commonly used environments, so
- algorithm, algorithmic
- table, tabular
- figure, subfigure
- anything else?

**Comment by jnegrea** [comment]
I think then that I can make a macro-generating macro to make 
\newcommand{\b##1}{\begin{##2}} 
\newcommand{\e##1}{\end{##2}}  
for all (##1 in #1, ##2 in #2)
something like that... where #1 and #2 are the lists of commands and shorthands resp. 
idk if this is better/simpler then just having these written our for all the commands and shorthands we want though

**Comment by trevorcampbell** [comment]
@jnegrea I like the idea. Would it clash with the definition of the `\b...` bold shortcuts? I suppose it's probably safe since these are all just macros for defining commands, but figured I'd check.

**Comment by jnegrea** [comment]
the meta-macro will have a different name from the other meta macro. 
the autogenerated macro will only conflict if an environment had the same name a a glyph we wanted to annotate. i think that is unlikely

**Comment by trevorcampbell** [comment]
We have a good way of doing this now as of #41. Closing
